config/routes.rb
Rails.application.routes.draw do
  resources :sales do
    collection do
      post :import
    end
  end
  resources :companies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'companies#show', id: '1'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/auction.rb
class Auction < ApplicationRecord
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :sale, dependent: :destroy
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :company
  validates :purchase_name, presence: true
  validates :item_price, presence: true
  validates :purchase_count, presence: true
  validates :merchant_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :find_or_create_ikli_company, only: %i[ index show edit update destroy ]
  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    def find_or_create_ikli_company
      @company = Company.find_by(name: 'IKLI TECNOLOGIA')
  
      unless @company
        @company = Company.create(name: 'IKLI TECNOLOGIA', amount: 0)
      end
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :amount)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  require 'csv'
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)
    @company = Company.find_by(name: 'IKLI TECNOLOGIA')
  
    @sale.company_id = @company.id if @company # Associa a venda à empresa apenas se a empresa for encontrada
      respond_to do |format|
        if @sale&.save
          @company.amount += (@sale.item_price.to_f * @sale.purchase_count.to_i) if @sale.item_price && @sale.purchase_count
          @company.save

          format.html { redirect_to root_path, notice: "Sale was successfully created." }
          format.json { render :show, status: :created, location: @sale }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @sale&.errors, status: :unprocessable_entity }
        end
      end
  end

  def import
    file = params[:file]
    return redirect_to new_sale_path, notice: 'Only CSV please' unless file.content_type == "text/csv"
    file = File.open(file)
    csv = CSV.parse(file, headers: true, col_sep: ';')
    
    csv.each do |row|
      sale_hash = {}
      sale_hash[:purchase_name] = row['purchase_name'].to_s
      sale_hash[:item_description] = row['item_description'].to_s
      sale_hash[:item_price] = row['item_price'].to_f
      sale_hash[:purchase_count] = row['purchase_count'].to_i
      sale_hash[:merchant_address] = row['merchant_address'].to_s
      sale_hash[:merchant_name] = row['merchant_name'].to_s
      sale_hash[:company_id] = 1 
      
      @sale = Sale.new(sale_hash)
      if @sale.save(validate: false)
        @company = Company.find_by(name: 'IKLI TECNOLOGIA')
        @company.amount += (@sale.item_price * @sale.purchase_count) if @sale.item_price && @sale.purchase_count
        @company.save
      end
      #binding.b
    end
    redirect_to sales_path, notice: 'Sales imported'
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy

    @company = Company.find_by(name: 'IKLI TECNOLOGIA')
    @company.amount -= (@sale.item_price * @sale.purchase_count) if @sale.item_price && @sale.purchase_count
    @company.save

    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:purchase_name, :item_description, :item_price, :purchase_count, :merchant_address, :merchant_name, :company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">
  <p>
    <strong>Name:</strong>
    <%= company.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= company.amount %>
  </p>

</div>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>
  <hr>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back to Home", company_path %>
</div>

app/views/companies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Companies</h1>

<div id="companies">
  <% @companies.each do |company| %>
    <%= render company %>
    <p>
      <%= link_to "Show this company", company %>
    </p>
  <% end %>
</div>

<%= link_to "New company", new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render "form", company: @company %>

<br>

<div>
  <%= link_to "Back to companies", companies_path %>
</div>

app/views/companies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @company %>

<div>
  <%= link_to "Edit this company", edit_company_path(@company) %> |
  <%= link_to "Show sales", sales_path %> |
  <%= link_to "New sale", new_sale_path %>
  <hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesOrganization</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/_form.html.erb
<%= form_with(model: sale, url: sales_path, multipart: true) do |form| %>
  <% if sale.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% sale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :purchase_name, style: "display: block" %>
    <%= form.text_field :purchase_name %>
  </div>

  <div>
    <%= form.label :item_description, style: "display: block" %>
    <%= form.text_field :item_description %>
  </div>

  <div>
    <%= form.label :item_price, style: "display: block" %>
    <%= form.text_field :item_price %>
  </div>

  <div>
    <%= form.label :purchase_count, style: "display: block" %>
    <%= form.number_field :purchase_count %>
  </div>

  <div>
    <%= form.label :merchant_address, style: "display: block" %>
    <%= form.text_field :merchant_address %>
  </div>

  <div>
    <%= form.label :merchant_name, style: "display: block" %>
    <%= form.text_field :merchant_name %>
  </div>

  <hr>

  <div>
    <%= form.submit 'Create sale', name: 'create_button' %>
  </div>
<% end %>

app/views/sales/_sale.html.erb
<div id="<%= dom_id sale %>">
  <p>
    <strong>Purchase name:</strong>
    <%= sale.purchase_name %>
  </p>

  <p>
    <strong>Item description:</strong>
    <%= sale.item_description %>
  </p>

  <p>
    <strong>Item price:</strong>
    <%= sale.item_price %>
  </p>

  <p>
    <strong>Purchase count:</strong>
    <%= sale.purchase_count %>
  </p>

  <p>
    <strong>Merchant address:</strong>
    <%= sale.merchant_address %>
  </p>

  <p>
    <strong>Merchant name:</strong>
    <%= sale.merchant_name %>
  </p>

</div>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render "form", sale: @sale %>

<br>

<div>
  <%= link_to "Show this sale", @sale %> |
  <%= link_to "Back to sales", sales_path %>
</div>

app/views/sales/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sales</h1>
<%= link_to "Back to Home", company_path(1) %>
<hr>

<div id="sales">
  <% @sales.each do |sale| %>
    <%= render sale %>
    <p>
      <%= link_to "Show this sale", sale %>
    </p>
    <hr>
  <% end %>
</div>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render "form", sale: @sale %>

<br>

<p>Or update your sales withing CSV</p>
<%= form_with url:import_sales_path, method: :post do |form|%>
  <%= form.file_field :file, accept: ".csv"%>
  <%= form.button "import"%>
<% end %>

<hr>
<div>
  <%= link_to "Back to Home", company_path(1) %>
</div>

app/views/sales/show.html.erb
<p style="color: green"><%= notice %></p>
<h1><%= @sale.merchant_name %> company purchases</h1>
<hr>
<%= render @sale %>

<div>
  <%= link_to "Edit this sale", edit_sale_path(@sale) %> |
  <%= link_to "Back to sales", sales_path %> |
  <%= link_to "Back to Home", company_path(1) %>
  <hr>

  <%= button_to "Destroy this sale", @sale, method: :delete %>
</div>